#!/bin/sh -eu

if [ $# -lt 3 ]; then
	echo "$0 host rssdir email md" >&2
	exit 1
fi

host="$1"
rssdir="$2"
email="$3"
md="$4"

${LOWDOWN:-lowdown} -t html "$md" | sed "s|@HOST@|$host|g"

if [ "${md#$rssdir/}" != "$md" ] && [ "${md#$rssdir/}" != "index.md" ]; then
	echo -n '<hr/>'
	echo -n '<a id="discuss" href="mailto:'
	echo -n "$email?subject=[Discuss]%20$(sed 's/ /%20/g' ${md%.md}.title)"
	echo -n '">Discuss</a>'
fi
