#!/bin/sh -eu

if [ $# -ne 2 ]; then
	echo "$0 svg outdir" >&2
	exit 1
fi

svg="$1"
outdir="$2"

name=$(basename "${svg%.svg}")

for n in 16 24 32 48 64 128 256 512 1024 2048 4096; do
	if [ -f "$outdir/$name$n.png" ]; then
		continue
	fi

	printf "Generating $outdir/$name$n.png."

	${INKSCAPE:-inkscape} -w $n -h $n "$svg" -o "$outdir/$name$n.png"

	printf "\r\033[KGenerated $outdir/$name$n.png.\n"
done
