#!/bin/sh -eu

if [ $# -lt 3 ]; then
	echo "$0 host md [discussemail]" >&2
	exit 1
fi

host="$1"
md="$2"
discussemail="${3:-}"

${LOWDOWN:-lowdown} -t html "$md" | sed "s|@HOST@|$host|g"

if [ -n "$discussemail" ]; then
	echo -n '<hr/>'
	echo -n '<a id="discuss" href="mailto:'
	echo -n "$discussemail?subject=[Discuss]%20"
	echo -n "$(sed 's/ /%20/g' ${md%.md}.title)"
	echo -n '">Discuss</a>'
fi
