#!/bin/sh -eu

if [ $# -lt 5 ]
then
	echo "$0 sitetitle host md header footer [discussemail]" >&2
	exit 1
fi

sitetitle="$1"
host="$2"
md="$3"
header="$4"
footer="$5"
discussemail="${6:-}"

descfile="${md%.md}.desc"
titlefile="${md%.md}.title"

if [ ! -r "$descfile" ]
then
	echo "File $descfile does not exist or is not readable." >&2
	exit 1
fi

rawdesc=$(cat "$descfile")
desc=$(echo -n "$rawdesc" | tr '\n' ' ')

if [ -r "$titlefile" ]
then
	rawtitle=$(cat "$titlefile")
	title=$(echo -n "$rawtitle" | tr '/n' ' ')
	fulltitle="$sitetitle — $title"
else
	fulltitle="$sitetitle"
fi

tail -n +2 "$header" | sed '/<!-- - -->/,$d' \
                     | sed "s/@DESCRIPTION@/$desc/g" \
                     | sed "s/@TITLE@/$fulltitle/g" \
                     | ./scripts/minimize

./scripts/gethtml "$host" "$md" "$discussemail"

tail -n +2 "$footer" | sed '1,/<!-- - -->/d' | ./scripts/minimize
