#!/bin/sh -eu

if [ $# -lt 3 ]; then
	echo "$0 sitetitle host md [discussemail]" >&2
	exit 1
fi

sitetitle="$1"
host="$2"
md="$3"
discussemail="${4:-}"

desc="${md%.md}.desc"
title="${md%.md}.title"

if [ ! -r "$desc" ]; then
	echo "File $desc does not exist or is not readable." >&2
	exit 1
fi

description="$(cat $desc | tr '\n' ' ')"

if [ -r "$title" ]; then
	fulltitle="$sitetitle — $(cat $title)"
else
	fulltitle="$sitetitle"
fi

cat header.html | sed "s/@DESCRIPTION@/$description/g" \
                | sed "s/@TITLE@/$fulltitle/g" \
                | tr -d '\n\t' \
                | sed -e 's/  \+/ /g' \

./scripts/gethtml "$host" "$md" "$discussemail"

cat footer.html | tr -d '\n\t' | sed -e 's/  \+/ /g'
