#!/bin/sh -eu

if [ $# -lt 5 ]; then
	echo "$0 sitetitle host md header footer [discussemail]" >&2
	exit 1
fi

sitetitle="$1"
host="$2"
md="$3"
header="$4"
footer="$5"
discussemail="${6:-}"

desc="${md%.md}.desc"
title="${md%.md}.title"

if [ ! -r "$desc" ]; then
	echo "File $desc does not exist or is not readable." >&2
	exit 1
fi

description="$(cat $desc | tr '\n' ' ')"

if [ -r "$title" ]; then
	fulltitle="$sitetitle — $(cat $title)"
else
	fulltitle="$sitetitle"
fi

cat "$header" | sed "s/@DESCRIPTION@/$description/g" \
              | sed "s/@TITLE@/$fulltitle/g" \
              | ./scripts/minimize

./scripts/gethtml "$host" "$md" "$discussemail"

cat "$footer" | ./scripts/minimize
