#!/bin/sh -eu

# ISO time format.
timefmt='%Y-%m-%dT%H:%M:%S%:z'

if [ $# -lt 2 ]; then
	echo "$0 host basedir [page ...]" >&2
	exit 1
fi

host="$1"
basedir="$2"

shift 2

printf '<?xml version="1.0" encoding="UTF-8"?>'
printf '<urlset xmlns="http://www.sitemaps.org/schemas/0.9">'

for p in $@; do
	relp="${p#$basedir/}"

	# Only have the path contain a trailing "/*.md" for pages which are
	# not index files; if they are, just use the directory as the path.
	if [ "$relp" = 'index.md' ]; then
		path=''
	elif [ "$(echo $relp | tail -c 10)" = '/index.md' ]; then
		path="$(dirname $relp)/"
	else
		path="$relp"
	fi

	# Retrieve last modification timestamp lastmodts and set lastmod to the
	# formatted time.
	lastmodts=$(tail -n +2 "$p.time")
	lastmod=$(date -u -d @"$lastmodts" +"$timefmt")

	printf '<url>'

	printf "<loc>https://$host/$path</loc>"
	printf "<lastmod>$lastmod</lastmod>"

	printf '</url>'
done

printf '</urlset>'

printf '\n'
